title: "Antares Programming"
description: "Web technologies for aspiring Filipino web developers."
permalink: /blog/:title/
theme-color: "#FF9500"
gravatar: aeec9ba19ac358be11a053ffcafac8f1
author: Francis Rubio
seo_image: /images/seo_image.png

facebook: antaresprogramming
mastodon: 
reddit: 
twitter: antaresphdev

authors:
  teacherbuknoy:
    name: Francis Rubio
    description: "Web developer, web designer, and educator from the Philippines"
    gravatar: 2dc37e96621279e556480e63b75b58dc # Gravatar md5 hash
    twitter: teacherbuknoy
  anonymous:
    name: "Unknown Author"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/articles/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor, create-new-post]

collections:
  courses:
    output: true
    
sass:
  sourcemap: always
